import extractors
import creds
import requests
import random


college_engg = {
    1601: 'Chaitanya Bharathi Institute of Technology',
    1602: 'Vasavi College of Engineering',
    2451: 'MVSR Engineering College',
    1604: 'Muffakham Jah College of Engineering and Technology',
    1603: 'Deccan College of Engineering and Technology',
    1605: 'ISL Womens Engineering College',
    1606: 'Stanley College of Engineering and Technology for Women',
    1607: 'Methodist College of Engineering and Technology',
    2452: 'Swathi Institute of Technology & Science',
    1608: 'Matrusri Engineering College'
}
course_engg = {
    1601: ['be', 'me', 'mtech'],
    1602: ['be', 'me', 'mtech'],
    2451: ['be', 'me', 'mtech'],
    1604: ['be', 'me', 'mtech'],
    1603: ['be', 'me', 'mtech'],
    1605: ['be'],
    1606: ['be', 'mtech'],
    1607: ['be', 'me'],
    2452: ['be', 'me', 'mtech'],
    1608: ['be']
}
college_mang = {
    1053: 'A.V. College of Arts',
    1077: 'DeccanSchool of Management',
    1111: 'Kasturba Gandhi PG College for Women',
    1117: 'LoyolaAcademyDegree & PGCollege',
    1157: 'PragathiMahavidyalayaP.G.College',
    1168: 'R.G.R.SiddhanthiCollege',
    1170: 'RG KediaCollege of Commerce',
    1173: 'RishiUBRP.G.College for Women',
    1174: 'S.D.SignodiaCollege of Arts & Com. &P.G.Centre',
    1175: 'S.N.VanithaMahavidyalayaCollege for Women',
    1189: 'SardarPatelCollege',
    1204: "St.Ann'sP.G.College for Women P.G.Centre",
    1206: 'St.AnnsP.G.College for Women',
    1214: "St.Joseph'sP.G.College",
    1238: 'Villa Marie P.G.College for Women',
    1245: 'VivekanadaSchool of P.G.Studies',
    1251: 'Wesley P.G.College',
    1301: 'AMSSchool of Informatics',
    1302: 'Aurora’s P.G.College-MBA) (formerlyAurora’s Management and Research Academy)',
    1303: 'Aurora’s P.G.College (MBA)',
    1304: 'Aurora’s P.G.College (MCA)',
    1305: 'AvanthiP.G.College',
    1306: 'Basaveshwara Institute of Information Technology',
    1307: 'Bharat P.G.College for Women',
    1309: 'Holy Mary Institute of Technology &Management',
    1311: 'Holy Mother P.G.College',
    1312: 'Malla Reddy Institute of Management',
    1313: 'Matrusri Institute of P.G.Studies',
    1314: 'MESCO Institute of Management & Computer Science',
    1315: 'NavabharathiCollege of P.G.Studies',
    1316: 'Presidency School of Management & Computer Sciences',
    1317: 'PrincetonP.G.College of Information Technology',
    1318: 'PrincetonP.G.College of Management (formerly Princeton P.G.College-MBA)',
    1319: 'PriyadarshiniCollege of Business Management',
    1320: 'PriyadarshiniCollege of Computer Science & Research',
    1321: 'Sai SudhirP.G.College',
    1322: 'Sri InduP.G.College',
    1323: 'Swamy Vivekananda P.G.College',
    1325: 'Aurora’s P.G.College-MCA',
    1401: 'Al-Quarmoshi Institute of Business Management',
    1402: 'AmjadAliKhanCollege of Business Administration',
    1403: 'Anwar-Ul-Uloom College of Business Management',
    1404: 'Apollo Institute of HospitalAdministrationApolloHospital Campus',
    1405: 'Badruka College  PG Centre',
    1406: 'BharathiyaVidyaBhawans Vivekananda College  of  Science',
    1407: 'David Memorial Institute of Management',
    1408: 'Dr.B.R.Ambedkar Institute of Management & Technology',
    1410: 'HyderabadSchool of Management',
    1411: 'Institute of Computers & Business Management (ICBM)',
    1412: 'MANTRASchool of Business Management',
    1413: 'Moghul College of Business Management',
    1415: 'Pendekanti Institute  of Management',
    1416: 'RBVRRCollege for Women',
    1417: 'Shadan Institute of Management Studies for Boys',
    1418: 'Shadan Institute of Management Studies for Gilrs',
    1419: 'ShahjahanCollege of Business Management',
    1420: 'V.V.College of Arts',
    1421: 'AndhraYuvathiMandaliSchool of Business for Women',
    1422: 'CSI Institute of P.G.Studies ',
    1423: 'St.Martin’sInstitute of Business Management',
    1424: 'St.Pious X PG (MBA) College for Women Snehapur Colony',
    1501: 'AnwarulUloomCollege of Computer Studies',
    1509: 'ManpowerDevelopmentCollege Opp.Kushaiguda Bus Depot',
    1511: 'Pulla Reddy Institute of Computer Sciences',
    1512: 'R.B.V.R.R.Institute of Technology',
    1515: 'Shadan Institute of Computer Studies for Boys',
    1516: 'Shadan Institute of Computer Studies for Girls',
    1601: 'ChaitanyaBharathi Institute of Technology',
    1605: 'ISL Womens Engineering College (formerly Islamia College of Engineering & Technology for Women',
    1606: 'StanleyCollege of Engineering & Technology for Women',
    1607: 'MethodistCollege of Engineering & Technology',
    2121: 'Aristotle P.G.College',
    2122: 'Aurora’s P.G.College-MBA',
    2125: 'EinsteinCollege of Business Management (formerly Einstein P.G.College-MBA)',
    2126: 'VishwaVishwani Institute of Technology Thumkunta',
    2128: 'HyderabadPresidencyCollege',
    2129: 'Aurora’s P.G.College-MCA',
    2130: 'KarunaP.G.College of Business Management',
    2131: 'KingstonP.G.College',
    2132: 'KRR Institute of Information Technology',
    2135: 'Mother Teresa College of Management & Computer Applications',
    2137: 'Mother Teresa P.G.College',
    2138: 'MRM Institute of Management',
    2139: 'Noble P.G.College',
    2142: 'Aurobindo Institute of Computer Sciences (formerly Olive P.G.College-MCA) Chintapallyguda',
    2143: 'Aurobindo College of Business Management',
    2144: 'OmegaCollege of Business Management (Omega P.G.College-MBA)',
    2145: 'PragnaP.G.College',
    2146: 'PRR College of Commerce & Management',
    2148: 'ReahSchool of Business Management',
    2149: 'Ronald Ross P.G.College of Computer Science',
    2150: 'Ronald Ross PG.College of Management Studies',
    2152: 'Sri Indu Institute of Management',
    2153: 'St.Anthony’sP.G.College',
    2154: 'St.AugistineP.G.College',
    2156: 'St.John’s Institute of Science & Technology',
    2159: 'St.Paul’s College of Management & Information Technology',
    2162: 'St.VincentP.G.College',
    2163: 'St.XavierP.G.College',
    2165: 'Suprabhath Institute of Computer Studies',
    2166: 'Suprabhat Institute of Management Cheeryal',
    2168: 'VidyaDayaniCollege of Information Technology',
    2169: 'VijayaP.G.College',
    2170: 'VishwaVishwani Institute of Systems & Management',
    2171: 'VivekanandaP.G.College',
    2174: 'Omega P.G.College-MCA',
    2252: 'Azad Institute of Management',
    2253: 'Bright  Institute of Management',
    2254: 'Global Education Centre',
    2256: 'KGR Institute of Technology & Management',
    2257: 'Krishnamurthy Institute of Management',
    2258: 'Siddhartha Institute of Computer Science',
    2260: 'TKR Institute of  Management & Science',
    2261: 'VijayaSchool of Business Management',
    2262: 'Academy of Management Studies',
    2265: 'Gandhian Institute of Management',
    2266: 'Global Institute of Management',
    2267: 'HashvithaP.G.College',
    2268: 'Institute of Management Studies P.G.Centre',
    2269: 'P.V.Ram Reddy P.G.College',
    2270: 'London Management Academy (formerly S.V.Model College of Management)',
    2271: 'S.V.R.School of Business Management',
    2273: 'SaanviP.G.College for Women',
    2275: 'TMSSCollege of Management',
    2276: 'Vision P.G.College',
    2278: 'VishwaVishwani School of Business Hyderabad',
    2279: 'Siddhartha Institute  Technology & Sciences',
    2280: 'St.Francis Institute of Management Gagillapur (V)',
    2281: 'AradhanaSchool of Business Management Kismathpura (V)',
    2282: 'KommuriPratap Reddy Institute of Management',
    2283: 'Pannala Ram Reddy College of Business Management',
    2354: 'Horizon Institute of Technology',
    2355: 'Jesus P.G.College',
    2356: 'KarunaP.G.College of Computer Applications',
    2357: 'Maryum Institute of Computer Science Chilkur (V)',
    2358: 'Samskruthi Institute of Business Management',
    2365: 'Sri Chakra Institute of Computer Sciences',
    2366: 'St.John’sP.G.College',
    2451: 'M.V.S.R.EngineeringCollege',
    6173: 'VinayakaCollege of I.T. & Business Management',
    6174: 'Sri BalajiP.G.College'
}
course_mang = {
    x: ['mba', 'bba'] for x in college_mang.keys()
}
college_ug = {
    # 1010: 'PG College',
    # 1011: 'PG College of Science',
    # 1051: 'Aurora Degree College',
    # 1053: 'A.V. Degree College',
    # 1054: 'A.K. Navajeevan Degree Coll. for Women',
    # 1055: 'ACME Degree College',
    # 1056: 'Kranthi Degree College',
    # 1057: 'Andhra Yuvathi Mandali Degree College for Women',
    # 1059: 'Avanthi Degree College',
    # 1060: 'Annie Besant Womens Degree College',
    # 1061: 'Arunodaya Degree College',
    # 1064: 'Badruka Degree College (Day)',
    # 1065: 'Badruka Degree College (AN)',
    # 1066: 'BBCIT',
    # 1068: 'Bhavans New Science Degree College (Day)',
    # 1069: 'Bhavans New Science Degree College (AN)',
    # 1070: 'BJR Govt. Degree College',
    # 1071: 'Bharat Degree College for Women',
    # 1072: 'Bhavans Viveknanda Degree College',
    # 1074: 'CAT Degree & PG College',
    # 1075: 'Dharmavanth Degree College',
    # 1076: 'Dr. B. R. Ambedkar Degree College',
    # 1078: 'Dewan Bahadur Padma Rao Modiliar Degree College for Women',
    # 1079: 'D.V.M Degree College of Commerce & Science',
    # 1080: 'Don Bosco Degree College',
    # 1081: 'David Memorial Degree College',
    # 1083: 'Govt. Degree College for Women',
    # 1086: 'G.M. Sanghi Degree College',
    # 1087: 'Gauthami Degree College',
    # 1088: 'Gauthami Degree College',
    # 1089: 'G. Pulla Reddy Degree College',
    # 1090: 'Geetanjali Degree College for Women',
    # 1091: 'Gokul Degree College',
    # 1093: 'Sree Venkateshwara Degree College',
    # 1094: 'Haindavi Degree College',
    # 1095: 'HRD Degree College',
    # 1096: 'Hindu Degree College for Women',
    # 1099: 'Hellen Kellers Instiute of Mentally Disabled',
    # 1100: 'IIMC Degree College',
    # 1101: 'Indira Priyadarshini Govt. Degree College for Women',
    # 1102: 'Islamia Degree College',
    # 1103: 'Indira Gandhi Degree College for Women',
    # 1104: 'Ideal Degree College for women',
    # 1105: 'Jagruthi Degree College',
    # 1106: 'Jahanavi Degree College',
    # 1107: 'Jahanavi Degree College',
    # 1108: 'Jahanavi Degree College for Women',
    # 1109: 'Jagruthi Degree College',
    # 1110: 'Keshav Memorial Institute of Commerce & Science',
    # 1111: 'Kasturba Gandhi Degree College for Women',
    # 1112: 'KEN Degree College',
    # 1113: 'K.V. Ranga Reddy Degree College for Women',
    # 1114: 'Sree Uma Degree college',
    # 1115: 'Kakitya Degree College',
    # 1116: 'L.N. Gupta Degree college',
    # 1118: 'Lal Bahadur Degree College',
    # 1119: 'ANURAG DEGREE & P G COLLEGE',
    # 1120: 'Little Flower Degree college',
    # 1121: 'Matrusree College of Graduate Studies',
    # 1122: 'Mumtaz Degree College',
    # 1123: 'MNR Degree College',
    # 1124: 'Musheerabad Degree College for Women',
    # 1125: 'Methodist Degree College',
    # 1126: 'Madina Degree College',
    # 1127: 'Mahaboob Degree College',
    # 1128: 'Maitreyi Womens degree College',
    # 1129: 'Visinoary Degree College',
    # 1130: 'Mega Womens Degree College',
    # 1131: 'ROYAL DEGREE COLLEGE',
    # 1132: 'Mesco Degree College',
    # 1133: 'Cognizant Degree College',
    # 1134: 'Megana Degree College',
    # 1135: 'N.B. Science Degree College',
    # 1136: 'New Siddhartha Degree College for Women',
    # 1137: 'National Degree College',
    # 1138: 'R.K.Degree College',
    # 1139: 'New Science Degree College',
    # 1140: 'New Govt. Degree College',
    # 1141: 'Nruputunga Degree College',
    # 1142: 'Noble Degree College',
    # 1143: 'Pasha New Noble Degree College',
    # 1144: 'New Scholars Degree College',
    # 1145: 'Vasundara Degree College (Co-Ed) 5-12- 236/1/A Mangapuram',
    # 1148: 'Nava Chaitanya Degree College',
    # 1150: 'New Silver Jubilee Degree College',
    # 1151: 'Omega Degree College',
    # 1152: 'Omega Degree College',
    # 1153: 'Pioneer Degree College',
    # 1154: 'Pragathi Degree College for Women',
    # 1155: 'Pragathi Degree college (Co-Ed.',
    # 1156: 'Pragathi Degree College for Women',
    # 1157: 'Pragathi Mahavidyalaya Degree College',
    # 1158: 'Princenton Degree College',
    # 1159: 'Princess Shehkar Degree College for Women',
    # 1160: 'Priyadarshini Degree College',
    # 1161: 'Pratibha Degree College',
    # 1162: 'Priyanka Degree College for Women',
    # 1163: 'Sri Ram Degree College',
    # 1164: 'Siddhartha Degree & P.G. College',
    # 1165: 'Vasundara Degree college (Co-Ed)',
    # 1166: 'Radhe Krishna Degree college',
    # 1167: 'Railway Degree College',
    # 1168: 'RGR Siddhanthi degree College',
    # 1169: 'Rishi Degree College',
    # 1170: 'R.G. Kedia Degree College',
    # 1171: 'Road Mystry Degree College',
    # 1173: 'Rishi UBR Degree College for Women',
    # 1174: 'S.D. Signodia Degree College',
    # 1175: 'S.N. Vanitha Degree College',
    # 1176: 'Sai Sudhir Degree College',
    # 1177: 'Samatha Degree College',
    # 1179: 'Scholars Womens Degree College',
    # 1180: 'Shadan Degree College for Men',
    # 1181: 'Shadan Degree College for Women',
    # 1182: 'Shantinikethan Degree College for Women',
    # 1183: 'Saradha Degree College for Women',
    # 1184: 'Shivani Womens Degree College',
    # 1186: 'Siddhartha degree College',
    # 1187: 'Siddhartaha Degree College for Women',
    # 1188: 'S.N. Degree College',
    # 1189: 'SP Degree College',
    # 1190: 'Sri Padmavathi Mahila Kalasala',
    # 1191: 'Spoorthy Degree & P.G. College',
    # 1193: 'Sri Aurbindo Degree College',
    # 1194: 'Sri Nagarjuna Degree College',
    # 1195: 'Sri Gujarathi Vidya Mandir',
    # 1197: 'Sri Pannalal Pitti Degree College for W',
    # 1198: 'Sri Ramchandra Degree College',
    # 1199: 'Sri Sai Degree College',
    # 1200: 'Sri Sai Vignan Bharathi Degree College',
    # 1201: 'Bhagyaradhi Degree College',
    # 1202: 'Sri Shardha degree college for Women',
    # 1203: 'Sri Vani Degree College',
    # 1204: 'St. Anns Degree College for Women',
    # 1205: 'St. Anns Degree College for Women',
    # 1206: 'St. Anns Degree College for Women',
    # 1207: 'St. Francis Xavier Degree College',
    # 1208: 'St. George Degree College for Women',
    # 1209: 'St. Mary Degree College',
    # 1210: 'St. Patricks Degree College',
    # 1211: 'St. Pauls Degree College',
    # 1212: 'St. Pious Degree College for Women',
    # 1215: 'Stannly degree college',
    # 1216: 'Sujatha Degree College for Women',
    # 1217: 'S V G Degree College',
    # 1218: 'Swathi Degree College',
    # 1220: 'Silver Jubilee Degree College',
    # 1221: 'Vahini Degree College',
    # 1222: 'St. Mary’s Centenary Degree College',
    # 1223: 'Sindhu Degree College',
    # 1224: 'Sir Newtons Degree College',
    # 1225: 'Sreenidhi Degree College',
    # 1226: 'saketa degree college',
    # 1227: 'St. Daniels Degree College',
    # 1229: 'The Mothers Degree College',
    # 1230: 'TMSS Degree College for Women',
    # 1231: 'Ushodaya Mahila Degree College',
    # 1232: 'Urdu Arts College (Eve)',
    # 1233: 'Vandana Degree College',
    # 1234: 'Vijayanagar College of Commerce',
    # 1235: 'Vidya Dayani Degree College for Women',
    # 1236: 'Vijetha Degree College',
    # 1237: 'Vikas Degree College',
    # 1238: 'Villa Marie Degree College for Women',
    # 1240: 'Vivekananda Degree College',
    # 1241: 'Pragnya Degree College',
    # 1243: 'Vasundara Womens Degree College',
    # 1244: 'Viveknanda Govt. Degree College',
    # 1246: 'V.V. College (Day) Jambagh',
    # 1247: 'V.V. College (AN) Jambagh',
    # 1248: 'Vani Degree College for Women',
    # 1249: 'Vijaya Karans Degree College',
    # 1250: 'Vivekananda Degree College',
    # 1251: 'Wesley Degree College',
    # 1252: 'Wesley Degree College for Girls',
    # 1256: 'St. Josephs Degree College for Women',
    # 1257: 'International Degree College',
    # 1258: 'MS Degree College for Women',
    # 1259: 'Limara Degree College',
    # 1260: 'Narayana Degree College',
    # 1262: 'New Madina Degree College',
    # 1263: 'St. Mary’s College',
    # 1264: 'Haindavi Degree College',
    # 1268: 'Aliens Degree College',
    # 1269: 'Harshini Degree College',
    # 1270: 'Azam Degree College',
    # 1271: 'Unique Degree College for Women',
    # 1272: 'ISO Degree College',
    # 1273: 'Royale Degree College for Women',
    # 1274: 'MS Degree College for Women',
    # 1275: 'MS Degree College for Women',
    # 1276: 'MS Degree College for Women',
    # 1277: 'Sree Venkateshwara Degree College',
    # 1278: 'Galaxy Degree college',
    # 1279: 'Siddhartha Degree College',
    # 1280: 'Roots Degree College',
    # 1281: 'Vignan Jyothi Institute of Arts',
    # 1282: 'Siddhartha Womens Degree College',
    # 1289: 'ETHAMES DEGREE COLLEGE',
    # 1290: 'Presidency Degree College for Commerce & Scie',
    # 1291: 'Madina Degree College',
    # 1292: 'The Progress Degree College',
    # 1293: 'HBS Degree College',
    # 1294: 'Haindavi Degree College',
    # 1295: 'Vignan Degree College',
    # 1296: 'Sri Chandra Degree Collge',
    # 1297: 'Sri Sarada Degree College (Co-Ed)',
    # 2001: 'Holy Cross Degree College for Women',
    # 2002: 'PMR Degree College',
    # 2003: 'Ibrahimpatnam Degree College',
    # 2004: 'Prathibha Degree College',
    # 2005: 'Pallavi Degree college',
    # 2006: 'Sri Ramalingeshwara Degree College',
    # 2007: 'Shalivahana Degree College',
    # 2008: 'SAP Degree College',
    # 2009: 'Takshashila Degree College',
    # 2010: 'Little Flower Degree College',
    # 2011: 'Peoples Degree College',
    # 2012: 'SIVA SIVANI DEGREE COLLEGE',
    # 2013: 'Sai Chaitanya Degree College',
    # 2014: 'S.V. Degree College',
    # 2015: 'Jagruthi Degree College',
    # 2016: 'Sri Sai Degree College',
    # 2017: 'Scholars Degree College',
    # 2018: 'Sai Gowthami Degree College',
    # 2019: 'Ashritha Womens Degree College',
    # 2020: 'Sri Venkateshwara Degree College',
    # 2022: 'Sri Saraswathi Vidyalaya Degree College',
    # 2023: 'New Adarsha Degree College',
    # 2024: 'Karanam Padmavathi Degree College',
    # 2025: 'Pranathi Degree College',
    # 2026: 'Vidyasagar Degree College',
    # 2027: 'Vishwa Bharathi Degree College',
    # 2029: 'Sri Sai Degree College',
    # 2030: 'New Sri Medha (Prajwala) Degree College',
    # 2031: 'Gauthami Degree College',
    # 2032: 'Sree Vignan Degree College',
    # 2033: 'St. Josehps College',
    # 2034: 'Vignan Degree College',
    # 2035: 'Jagruthi Degree College',
    # 2036: 'Sri Chaitanya Degree College',
    # 2037: 'Govt. Degree College',
    # 2038: 'Govt. Degree College',
    # 2039: 'Govt. Degree College',
    # 2040: 'Govt. Degree College',
    # 2041: 'Govt. Degree College',
    # 2042: 'Prathibha Degree College',
    # 2043: 'Mahila Dikshitha Samithi Degree College for Wo',
    # 2044: 'Sindhu Degree College',
    # 2045: 'Sri Vaagdevi Degree College',
    # 2051: 'Jagruthy Womens Degree College',
    # 2052: 'Netra Vidyalayam Degree College for Blind',
    # 2053: 'IITM',
    # 2054: 'Vanitha Degree College for Women',
    # 2055: 'Galaxy Degree College',
    # 2056: 'New Badruka Degree College',
    # 2057: 'PJRs Memorial Sai Teja Degree College',
    # 2058: 'Sai Teja Degree College',
    # 2059: 'Pragnya  Womens Degree College',
    # 2061: 'Pragathi Womens Degree college',
    # 2062: 'Rainbow Integrated Degree college',
    # 2064: 'Vishwa Chaitany Women’s Degree College',
    # 2066: 'Spandana Womens Degree College',
    # 2067: 'Frobel’s Degree College',
    # 2068: 'KLR Degree College',
    # 2069: 'Vignan Degree College',
    # 2070: 'Nagarjuna Degree College',
    # 2071: 'Bhavitha Degree College',
    # 2072: 'Siddhartha Degree College',
    # 2074: "Gowthami Women's Degree College Shamshaba",
    # 2075: 'Haindavi Degree College',
    # 2076: 'Vijetha Degree College for Women',
    # 2077: 'Sri Chaitanya Degree College',
    # 2079: 'Kavitha Degree College for Women',
    # 2080: 'Balaji Degree College',
    # 2081: 'Anish Degree College',
    # 2082: 'PMR Degree College',
    # 2083: 'Sahithi Degree College for Women',
    # 2084: 'Geethanjali Degree College',
    # 2085: 'Avinash Degree College',
    # 2087: 'Holy Mary Degree College',
    # 2088: 'Silver Jubilee Degree College for Women',
    # 2089: 'New Pragathi Degree College of Commerce & Sc',
    # 2090: 'Govt. Degree College',
    # 2091: 'Dr. Narayana Degree College of Commerce & Sc.',
    # 2092: 'Narayana Degree College',
    # 2093: 'Great India Degree College',
    # 2094: 'Sree Bindu Degree College',
    # 2095: 'Infant Jesus Degree College',
    # 2096: 'Saanvi Degree College for Women',
    # 2097: 'Akshara Degree College',
    # 6001: 'Vashista Degree College',
    # 6002: 'Acharya Degree College ',
    # 6004: 'Adharsha Degree College ',
    # 6005: 'Anuradha Memorial Degree Coll. ',
    # 6006: 'Baptist Degree College ',
    # 6007: 'BMR Degree College ',
    # 6008: 'BMR Degree College ',
    # 6012: 'Ellenki Degree College (Co-Education) ',
    # 6014: 'Ellenki Degree College ',
    # 6016: 'Geetanjali Degree College ',
    # 6017: 'Govt. Degree College for women ',
    # 6018: 'Govt. Degree College for Women ',
    # 6019: 'Govt.Degree College ',
    # 6020: 'Govt. Degree College ',
    # 6021: 'Govt. Degree College ',
    # 6022: 'Govt. Degree College ',
    # 6023: 'Govt. Degree College ',
    # 6024: 'Govt.Degree college for Women',
    # 6025: 'Govt. Degree College ',
    # 6026: 'Govt. Degree College ',
    # 6027: 'Govt.Degree College ',
    # 6028: 'Govt. Degree College (Co-Ed)',
    6029: 'Govt. Degree College for Women ',
    6031: 'Jagruthi Degree College ',
    6032: 'Manjeera Degree College',
    6033: 'Manjeera Degree College ',
    6034: 'MVG Memorial Degree Collegge',
    6035: 'Nagarjuna Degree College ',
    6036: 'Nagarjuna Degree College ',
    6037: 'Nalanda Degree College',
    6038: 'Nehru Memorial Govt. Degree College ',
    6039: 'Pratibha Degree College ',
    6040: 'Royal Degree College ',
    6041: "SVB (Master's) Degree College",
    6042: 'Sanga Mithra Degree College ',
    6043: 'Sarvepally Radhakrishna Degree College',
    6044: 'Sneha Degree College ',
    6045: 'Sri Chaitanya Degree College',
    6046: 'Sri Maruthi Degree College ',
    6047: 'Sri Padmanabha Degree College ',
    6048: 'Sri Sadana Degree College ',
    6049: 'Sri Sai Degree College ',
    6050: 'Sri Vani Degree College',
    6051: 'M.G Degree College',
    6052: 'Sri Venkateswara  Degree College ',
    6053: 'Sri Vidya Degree College',
    6054: 'Sri Viveka Vardhini Degree College ',
    6055: 'Srinidhi Degree College ',
    6056: 'Srinivasa Degree College  Brahim Street ',
    6057: 'Srinivasa Degree College ',
    6058: 'Tara Govt. College ',
    6059: 'Masters Degree College',
    6060: 'Vijaya Sai Degree College ',
    6061: 'YPR Degree College ',
    6062: 'Wisdom Degree College ',
    6063: 'Sri Chaintanay Degree college',
    6066: 'Government Degree College',
    6067: 'Sri Manikanta Saranam Degree College',
    6068: 'Government Degree College for Women',
    6070: 'Social Welfare Residential College for Girls',
    6071: 'Pattabhi Degree College',
    6072: 'Sri Vivekananda Degree College',
    6075: 'Sri Manikanta Sharanam Degree College',
    6076: 'Shivaji Degree College',
    6077: 'Aashritha Degree College',
    6078: 'Sri Yuva Chaitanya Degree College'
}
course_ug = {
    1010: ['bcom', 'bsc'],
    1011: ['bsc'],
    1051: ['bba', 'bcom', 'bsc'],
    1053: ['bcom', 'ba', 'bsc'],
    1054: ['bcom', 'bsc'],
    1055: ['bcom', 'bsc'],
    1056: ['bcom', 'bsc'],
    1057: ['bcom', 'bsc'],
    1059: ['bcom', 'bsc'],
    1060: ['bcom', 'ba', 'bsc'],
    1061: ['bcom', 'bsc'],
    1064: ['bba', 'bcom'],
    1065: ['bcom'],
    1066: ['bsc'],
    1068: ['bsc'],
    1069: ['bcom', 'ba'],
    1070: ['bcom', 'ba', 'bsc'],
    1071: ['bba', 'bcom'],
    1072: ['bcom', 'bba', 'ba', 'bsc'],
    1074: ['bcom', 'bsc'],
    1075: ['bcom', 'bsc'],
    1076: ['bcom', 'ba', 'bsc'],
    1078: ['bcom', 'bsc'],
    1079: ['bcom', 'bsc'],
    1080: ['bcom', 'bsc'],
    1081: ['bba', 'bcom', 'bsc'],
    1083: ['bcom', 'ba', 'bsc'],
    1086: ['bcom'],
    1087: ['bcom', 'bsc'],
    1088: ['bcom', 'bsc'],
    1089: ['bcom', 'bsc'],
    1090: ['bcom', 'bsc'],
    1091: ['bcom', 'bsc'],
    1093: ['bcom', 'bsc'],
    1094: ['bcom'],
    1095: ['bcom', 'bsc'],
    1096: ['bcom', 'bsc'],
    1099: ['bcom', 'bsc'],
    1100: ['bba', 'bcom', 'bsc'],
    1101: ['bcom', 'ba', 'bsc'],
    1102: ['bcom', 'ba', 'bsc'],
    1103: ['bcom', 'bsc'],
    1104: ['bcom', 'bsc'],
    1105: ['bba', 'bcom', 'bsc'],
    1106: ['bba', 'bcom', 'bsc'],
    1107: ['bba', 'bcom', 'bsc'],
    1108: ['bba', 'bcom', 'bsc'],
    1109: ['bcom', 'bsc'],
    1110: ['bcom', 'bsc'],
    1111: ['bcom', 'ba', 'bsc'],
    1112: ['bcom'],
    1113: ['bcom', 'bsc'],
    1114: ['bcom', 'bsc'],
    1115: ['bcom', 'bsc'],
    1116: ['bcom', 'bsc'],
    1118: ['bcom'],
    1119: ['bcom', 'bsc'],
    1120: ['bcom', 'bsc'],
    1121: ['bcom', 'bsc'],
    1122: ['bcom', 'bsc'],
    1123: ['bcom', 'bsc'],
    1124: ['bcom'],
    1125: ['bcom'],
    1126: ['bcom', 'bsc'],
    1127: ['bcom'],
    1128: ['bcom', 'bsc'],
    1129: ['bcom'],
    1130: ['bcom', 'bsc'],
    1131: ['bcom', 'bsc'],
    1132: ['bcom'],
    1133: ['bcom', 'bsc'],
    1134: ['bcom', 'bsc'],
    1135: ['bsc'],
    1136: ['bcom', 'ba', 'bsc'],
    1137: ['bcom', 'bsc'],
    1138: ['bcom'],
    1139: ['bcom', 'bsc'],
    1140: ['bcom', 'ba', 'bsc'],
    1141: ['bcom', 'bsc'],
    1142: ['bcom', 'ba', 'bsc'],
    1143: ['bba', 'bcom', 'bsc'],
    1144: ['bcom', 'bsc'],
    1145: ['bcom', 'bsc'],
    1148: ['bcom'],
    1150: ['bcom', 'bsc'],
    1151: ['bcom', 'bsc'],
    1152: ['bcom', 'bsc'],
    1153: ['bcom', 'bsc'],
    1154: ['bcom', 'bsc'],
    1155: ['bcom', 'bsc'],
    1156: ['bcom', 'bsc'],
    1157: ['bba', 'bcom', 'bsc'],
    1158: ['bcom', 'bsc'],
    1159: ['bcom', 'ba', 'bsc'],
    1160: ['bcom'],
    1161: ['bcom', 'bsc'],
    1162: ['bcom', 'bsc'],
    1163: ['bcom', 'ba', 'bsc'],
    1164: ['bcom', 'ba', 'bca', 'bsc'],
    1165: ['bcom', 'bsc'],
    1166: ['bcom'],
    1167: ['bcom', 'ba', 'bsc'],
    1168: ['bcom', 'bsc'],
    1169: ['bba', 'bcom', 'bsc'],
    1170: ['bba', 'bcom', 'bsc'],
    1171: ['bsw'],
    1173: ['bcom', 'bsc'],
    1174: ['bcom'],
    1175: ['bcom', 'ba', 'bsc'],
    1176: ['bcom', 'bsc'],
    1177: ['bcom', 'bsc'],
    1179: ['bcom', 'ba', 'bsc'],
    1180: ['bcom', 'bsc'],
    1181: ['bcom', 'ba', 'bsc'],
    1182: ['bcom', 'bsc'],
    1183: ['bcom', 'bsc'],
    1184: ['bcom', 'bsc'],
    1186: ['bcom', 'bsc'],
    1187: ['bcom', 'bsc'],
    1188: ['bcom', 'ba', 'bsc'],
    1189: ['bcom', 'ba', 'bsc'],
    1190: ['bcom'],
    1191: ['bcom', 'bsc'],
    1193: ['bcom', 'bsc'],
    1194: ['bcom', 'bsc'],
    1195: ['bcom'],
    1197: ['bcom', 'ba'],
    1198: ['bcom', 'bsc'],
    1199: ['bcom', 'bsc'],
    1200: ['bcom', 'bsc'],
    1201: ['bcom', 'bsc'],
    1202: ['bcom', 'bsc'],
    1203: ['bcom', 'ba', 'bsc'],
    1204: ['bcom', 'bba', 'ba', 'bsc'],
    1205: ['bcom', 'bsc'],
    1206: ['bcom', 'bsc'],
    1207: ['bcom', 'bsc'],
    1208: ['bcom'],
    1209: ['bcom', 'bba', 'ba', 'bsc'],
    1210: ['bcom', 'bsc'],
    1211: ['bba', 'bcom'],
    1212: ['bcom', 'bba', 'ba', 'bsc'],
    1215: ['bcom', 'bsc'],
    1216: ['bcom', 'bsc'],
    1217: ['bcom', 'bsc'],
    1218: ['bcom', 'bsc'],
    1220: ['bcom', 'bsc'],
    1221: ['bcom', 'bsc'],
    1222: ['bcom'],
    1223: ['bcom', 'bsc'],
    1224: ['bcom', 'bsc'],
    1225: ['bcom', 'bsc'],
    1226: ['bcom', 'bsc'],
    1227: ['bcom', 'bsc'],
    1229: ['bcom'],
    1230: ['bcom', 'ba', 'bsc'],
    1231: ['bcom'],
    1232: ['bcom', 'ba'],
    1233: ['bcom', 'bsc'],
    1234: ['bcom'],
    1235: ['bcom'],
    1236: ['bcom', 'bsc'],
    1237: ['bcom', 'bsc'],
    1238: ['bcom', 'bba', 'ba', 'bsc'],
    1240: ['bcom', 'bsc'],
    1241: ['bcom', 'bsc'],
    1243: ['bcom', 'bsc'],
    1244: ['bcom', 'ba', 'bsc'],
    1246: ['bcom', 'ba', 'bsc'],
    1247: ['bcom', 'ba'],
    1248: ['bcom'],
    1249: ['bcom', 'bsc'],
    1250: ['bcom', 'bsc'],
    1251: ['bcom', 'ba', 'bsc'],
    1252: ['bcom', 'ba', 'bsc'],
    1256: ['bcom', 'bsc'],
    1257: ['bcom', 'bsc'],
    1258: ['bcom', 'ba'],
    1259: ['bcom'],
    1260: ['ba'],
    1262: ['bcom'],
    1263: ['bcom', 'bsc'],
    1264: ['bcom', 'bsc'],
    1268: ['bcom', 'bsc'],
    1269: ['bcom'],
    1270: ['bcom', 'bsc'],
    1271: ['bcom', 'ba'],
    1272: ['bcom', 'bsc'],
    1273: ['bcom', 'bsc'],
    1274: ['bcom', 'bsc'],
    1275: ['bcom', 'bsc'],
    1276: ['bcom', 'bsc'],
    1277: ['bcom'],
    1278: ['bcom', 'ba', 'bsc'],
    1279: ['bcom', 'bsc'],
    1280: ['bba', 'ba'],
    1281: ['bcom', 'bba', 'ba', 'bsc'],
    1282: ['bcom', 'bsc'],
    1289: ['bcom', 'bba', 'ba'],
    1290: ['bcom', 'bsc'],
    1291: ['bcom', 'bsc'],
    1292: ['bcom', 'bsc'],
    1293: ['bba', 'ba'],
    1294: ['bcom', 'bsc'],
    1295: ['bba', 'bcom', 'bsc'],
    1296: ['bcom', 'bsc'],
    1297: ['bcom', 'bsc'],
    2001: ['bcom', 'bsc'],
    2002: ['bcom', 'ba', 'bsc'],
    2003: ['bcom', 'ba', 'bsc'],
    2004: ['bcom', 'ba', 'bsc'],
    2005: ['bcom', 'ba', 'bsc'],
    2006: ['bcom', 'ba'],
    2007: ['bcom', 'ba', 'bsc'],
    2008: ['bcom', 'ba', 'bsc'],
    2009: ['bcom', 'ba', 'bsc'],
    2010: ['bcom', 'ba', 'bsc'],
    2011: ['bcom', 'ba', 'bsc'],
    2012: ['bba', 'bcom', 'bsc'],
    2013: ['bcom', 'bsc'],
    2014: ['bcom', 'bsc'],
    2015: ['bcom', 'ba', 'bsc'],
    2016: ['bcom', 'ba'],
    2017: ['bcom', 'bsc'],
    2018: ['bcom', 'ba', 'bsc'],
    2019: ['bcom', 'ba', 'bsc'],
    2020: ['bcom', 'ba', 'bsc'],
    2022: ['bcom', 'ba', 'bsc'],
    2023: ['bcom', 'ba', 'bsc'],
    2024: ['ba', 'bsc'],
    2025: ['bcom', 'bsc'],
    2026: ['bcom', 'ba', 'bsc'],
    2027: ['ba', 'bsc'],
    2029: ['bcom', 'ba', 'bsc'],
    2030: ['bcom', 'ba', 'bsc'],
    2031: ['bcom', 'bsc'],
    2032: ['bcom', 'ba', 'bsc'],
    2033: ['bcom', 'ba'],
    2034: ['bcom', 'bsc'],
    2035: ['bcom', 'ba'],
    2036: ['bcom', 'bsc'],
    2037: ['bcom', 'ba', 'bsc'],
    2038: ['bcom', 'ba', 'bsc'],
    2039: ['bcom', 'ba', 'bsc'],
    2040: ['bcom', 'ba', 'bsc'],
    2041: ['bcom', 'ba', 'bsc'],
    2042: ['bcom', 'ba', 'bsc'],
    2043: ['bcom', 'bsc'],
    2044: ['bcom', 'ba', 'bsc'],
    2045: ['bcom', 'bsc'],
    2051: ['bcom', 'ba', 'bsc'],
    2052: ['bcom', 'ba'],
    2053: ['bcom', 'bsc'],
    2054: ['bcom', 'bsc'],
    2055: ['bcom', 'bsc'],
    2056: ['bcom', 'ba'],
    2057: ['bcom', 'bsc'],
    2058: ['bcom', 'ba', 'bsc'],
    2059: ['bcom', 'bsc'],
    2061: ['bcom', 'bsc'],
    2062: ['bcom', 'ba', 'bsc'],
    2064: ['ba', 'bcom', 'bsc'],
    2066: ['bcom', 'bsc'],
    2067: ['bcom', 'bsc'],
    2068: ['bcom', 'bsc'],
    2069: ['bcom', 'bsc'],
    2070: ['bcom', 'ba'],
    2071: ['bcom', 'bsc'],
    2072: ['bcom', 'ba'],
    2074: ['bcom', 'bsc'],
    2075: ['bcom', 'bsc'],
    2076: ['bcom', 'bsc'],
    2077: ['ba'],
    2079: ['bcom', 'ba'],
    2080: ['bcom', 'ba'],
    2081: ['bba', 'bcom'],
    2082: ['bcom', 'bsc'],
    2083: ['bcom', 'bsc'],
    2084: ['bcom', 'bsc'],
    2085: ['bcom', 'bba', 'ba'],
    2087: ['bba', 'bcom', 'bsc'],
    2088: ['bcom', 'bsc'],
    2089: ['bcom', 'bsc'],
    2090: ['bcom'],
    2091: ['bba', 'bsc'],
    2092: ['ba'],
    2093: ['bba'],
    2094: ['bcom', 'bsc'],
    2095: ['bcom', 'bsc'],
    2096: ['bcom', 'bsc'],
    2097: ['bcom', 'bsc'],
    6001: ['bcom', 'ba', 'bsc'],
    6002: ['bcom', 'ba', 'bsc'],
    6004: ['bcom', 'ba', 'bsc'],
    6005: ['bcom', 'ba', 'bsc'],
    6006: ['bcom', 'bsc'],
    6007: ['bcom', 'ba', 'bsc'],
    6008: ['bcom', 'ba', 'bsc'],
    6012: ['bcom', 'ba', 'bsc'],
    6014: ['bcom', 'bsc'],
    6016: ['bcom', 'ba', 'bsc'],
    6017: ['bcom', 'ba', 'bsc'],
    6018: ['bcom', 'ba', 'bsc'],
    6019: ['bcom', 'ba', 'bsc'],
    6020: ['bcom', 'ba', 'bsc'],
    6021: ['bcom', 'ba', 'bsc'],
    6022: ['bcom', 'ba', 'bsc'],
    6023: ['bcom', 'ba', 'bsc'],
    6024: ['bcom', 'ba', 'bsc'],
    6025: ['bcom', 'ba', 'bsc'],
    6026: ['bcom', 'ba', 'bsc'],
    6027: ['bcom', 'ba', 'bsc'],
    6028: ['bcom', 'ba', 'bsc'],
    6029: ['bcom', 'ba', 'bsc'],
    6031: ['bcom', 'ba', 'bsc'],
    6032: ['bcom', 'ba', 'bsc'],
    6033: ['bcom', 'ba', 'bsc'],
    6034: ['bcom', 'ba', 'bsc'],
    6035: ['bcom', 'bsc'],
    6036: ['bcom', 'ba', 'bsc'],
    6037: ['bcom', 'ba', 'bsc'],
    6038: ['bcom', 'ba', 'bsc'],
    6039: ['bcom', 'ba', 'bsc'],
    6040: ['bcom', 'ba', 'bsc'],
    6041: ['bcom', 'ba', 'bsc'],
    6042: ['bcom', 'ba', 'bsc'],
    6043: ['bcom', 'bsc'],
    6044: ['bcom', 'ba', 'bsc'],
    6045: ['ba'],
    6046: ['bcom', 'ba', 'bsc'],
    6047: ['bcom', 'bsc'],
    6048: ['bcom', 'ba', 'bsc'],
    6049: ['bcom', 'ba', 'bsc'],
    6050: ['bcom', 'ba', 'bsc'],
    6051: ['bcom', 'ba', 'bsc'],
    6052: ['ba'],
    6053: ['bcom', 'ba', 'bsc'],
    6054: ['bcom', 'ba', 'bsc'],
    6055: ['bcom', 'ba', 'bsc'],
    6056: ['ba', 'bsc'],
    6057: ['bcom', 'ba', 'bsc'],
    6058: ['bcom', 'ba', 'bsc'],
    6059: ['bcom', 'ba', 'bsc'],
    6060: ['bcom', 'ba', 'bsc'],
    6061: ['bcom', 'ba', 'bsc'],
    6062: ['bcom', 'ba', 'bsc'],
    6063: ['bcom', 'bsc'],
    6066: ['bcom', 'ba', 'bsc'],
    6067: ['bcom', 'ba'],
    6068: ['bcom', 'ba', 'bsc'],
    6070: ['bcom'],
    6071: ['bba', 'bcom', 'bsc'],
    6072: ['bcom', 'ba', 'bsc'],
    6075: ['ba', 'bsc'],
    6076: ['bcom', 'ba', 'bsc'],
    6077: ['bcom', 'ba', 'bsc'],
    6078: ['bcom', 'ba', 'bsc']
}
course_codes = {
    'bcom': [401, 402, 403, 404, 405, 406, 407, 420],
    'bsc': [441, 442, 443, 445, 447, 457, 458, 459, 460, 461, 462, 463, 464, 467, 468, 470, 471, 472, 474, 478, 480,
            481, 483, 484, 486, 487, 488, 489, 492, 569, 571, 572, 573, 574, 577, 578, 588, 589, 590, 600, 614],
    'ba': [111, 112, 114, 117, 122, 129, 130, 155, 156, 162, 236, 247, 258, 259, 260, 262, 263, 268, 272, 278, 352,
           354, 356, 357, 358, 361, 362, 364, 366, 367, 370, 372, 381, 386, 387, 388, 390, 391, 395, 397, 555, 666],
    'bba': [684],
    'ma': [9, 10, 11, 12, 13, 14, 15, 16, 18, 19, 20, 21, 22, 88, 313, 314, 315, 316, 317, 318],
    'mcom': [408, 409],
    'msc': [502, 503, 504, 505, 506, 507, 508, 509, 510, 511, 512, 513, 514, 515, 516, 517, 518, 519, 520, 522, 523,
            524, 525, 526, 528, 529, 584, 585, 586, 587, 605, 607],
    'mba': [672, 673, 675, 682],
    'bed': [705, 706, 707, 701],
    'med': [713, 714, 709],
    'btech': [802, 805],
    'bpharma': [881],
    'bca': [861],
    'mca': [862],
    'be': [732, 733, 734, 735, 736, 737, 738, 739, 769],
    'me': [741, 742, 743, 744, 765],
    'bsw': [777, 305]
}
course_duration = {
    'bcom': 3, 'bsc': 3, 'ba': 3, 'bba': 3, 'ma': 2, 'mcom': 2, 'msc': 2, 'mba': 2, 'bed': 1, 'med': 2, 'btech': 4,
    'bpharma': 4, 'bca': 3, 'mca': 3, 'be': 4, 'me': 2, 'bsw': 3
}

urls_2021 = {
    'ba': 'www.osmania.ac.in/res07/20210945.jsp',
    'bba': 'www.osmania.ac.in/res07/20210946.jsp',
    'bsc': 'www.osmania.ac.in/res07/20210948.jsp',
    'bcom': 'www.osmania.ac.in/res07/20210947.jsp',
}

urls = {
    21: urls_2021
}

headers = {
    'Accept': 'text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9',
    'Accept-Encoding': 'gzip, deflate, br',
    'Accept-Language': 'en-US,en;q=0.9',
    'Connection': 'keep-alive',
    'Content-Type': 'application/x-www-form-urlencoded',
    'Host': 'www.osmania.ac.in',
    'Origin': 'https://www.osmania.ac.in',
    'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/94.0.4606.81 Safari/537.36'
}


def create_payload(htno):
    """
    htno: str: hall ticket number
    return: str: payload
    """
    return f"mbstatus=SEARCH&htno={htno}&Submit.x={random.randint(1, 99)}&Submit.y={random.randint(1, 99)}"


def roll_no_generator(clg_code, yoa, crs_code, roll):
    """
    clg_code: int: college code
    yoa: str: year of admission
    crs_code: int: course code
    roll: int: roll number count
    return: str: generated roll number
    """
    no_of_zero = 3 - len(str(roll))
    roll = f'{"0"*no_of_zero}{roll}'
    return f"{clg_code}{yoa}{crs_code}{roll}"


def scrapping(type, yop, req=None):
    """
    type: str: type of education like engg for engineering, mang for management, ug for undergraduate
    yop: int: year of passing in YY format
    """
    roll = ""
    count = 0
    if req:
        user = req.user.pk
    else:
        user = req
    url = urls.get(yop)
    if not url:
        print('Api url not found !')
    if type == 'engg':
        college = college_engg
        course = course_engg
    elif type == 'mang':
        college = college_mang
        course = course_mang
    else:
        college = college_ug
        course = course_ug
    try:
        conn = creds.mysql_connect()
        for college_code, college_name in college.items():
            related_course = course[college_code]
            for rel_course in related_course:
                admission_year = yop - course_duration[rel_course]
                admission_year = f"0{admission_year}" if admission_year < 10 else str(admission_year)
                course_code = course_codes[rel_course]
                for crs_code in course_code:
                    thresh = 0
                    for i in range(1, 1000):
                        if college_code == 1260 and admission_year == "18" and crs_code <= 381 and i <= 160:
                            continue
                        count = i
                        roll = roll_no_generator(
                            clg_code=college_code,
                            yoa=admission_year,
                            crs_code=crs_code,
                            roll=i
                        )
                        query = creds.get_filter_data(
                            roll_no=roll,
                            board_id=11
                        )
                        try:
                            cursor = conn.cursor()
                        except:
                            conn = creds.mysql_connect()
                            cursor = conn.cursor()
                        cursor.execute(query)
                        _res = cursor.fetchall()
                        cursor.close()
                        if _res:
                            continue
                        api_url = url.get(rel_course)
                        if not api_url:
                            continue
                        res = None
                        if isinstance(api_url, list):
                            for api in api_url:
                                api = "https://" + api
                                _headers = headers
                                _headers['Referer'] = api
                                data = create_payload(roll)
                                try:
                                    res = requests.post(url=api, headers=_headers, data=data, timeout=10)
                                except:
                                    continue
                                res = res.text
                        else:
                            api_url = "https://" + api_url
                            # api_url = "https://www.osmania.ac.in/res07/20210945.jsp"
                            # roll = "105318111013"
                            _headers = headers
                            _headers['Referer'] = api_url
                            data = create_payload(roll)
                            try:
                                res = requests.post(url=api_url, headers=_headers, data=data, timeout=10)
                            except:
                                continue
                            res = res.text
                        if not res:
                            continue
                        scrap_data = extractors.scrap_osmania(
                            page_source=res,
                            college_name=college_name,
                            website=api_url,
                            roll=roll
                        )
                        if scrap_data['status']:
                            thresh = 0
                            if user:
                                scrap_data['created_by_id'] = user
                            insert_query = "INSERT INTO education (name, degree_name, roll_no, exam_result, website_url, filepath, board_id, created_at, updated_at, college_name, year_of_passing, father_name, gender, created_by_id) VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s)"
                            payload = (
                                scrap_data['name'],
                                scrap_data['degree_name'],
                                scrap_data['roll_no'],
                                scrap_data['exam_result'],
                                scrap_data['website_url'],
                                scrap_data['filepath'],
                                scrap_data['board_id'],
                                scrap_data['created_at'],
                                scrap_data['updated_at'],
                                scrap_data['college_name'],
                                scrap_data['year_of_passing'],
                                scrap_data['father_name'],
                                scrap_data['gender'],
                                scrap_data.get('created_by_id')
                            )
                            try:
                                cursor = conn.cursor()
                            except:
                                conn = creds.mysql_connect()
                                cursor = conn.cursor()
                            cursor.execute(insert_query, payload)
                            conn.commit()
                            cursor.close()
                        else:
                            if thresh > 100:
                                break
                            thresh += 1
            conn.close()
            print(college_name, ' -- Done')
            creds.send_mail(f"Osmania Scrapping -- Done till- {roll}", "Completed")
    except Exception as e:
        creds.send_mail(f'Error: Osmania Scrapping- {roll}', e.args[0])


if __name__ == '__main__':
    scrapping('ug', 21)
