# Generated by Django 4.1.7 on 2023-03-27 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                ("auto_id", models.AutoField(primary_key=True, serialize=False)),
                ("user_name", models.CharField(blank=True, max_length=20)),
                ("first_name", models.CharField(blank=True, max_length=30)),
                ("last_name", models.CharField(blank=True, max_length=40)),
            ],
        ),
    ]
